name: matrix
description: "a list of hunter's matrix's and just_audio to play them from archive.org"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.45+17

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  async: ^2.11.0
  logger: ^2.4.0
  just_audio: ^0.9.42
  just_audio_background: ^0.0.1-beta.13
  provider: ^6.1.2
  flash: ^3.1.1
  gap: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  audio_session: ^0.1.21
  http: ^1.2.2
  url_launcher: ^6.3.1
  marquee: ^2.2.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/data_opt.json
    - assets/archive_tracks_shnid_opt.json
    - assets/images/
    - assets/images/t_steal.webp
    - assets/audio/
    - assets/audio/HunterTrix105/
    - assets/images/trix_album_art/

